# Generated by Django 5.1.9 on 2025-06-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва сервісу')),
                ('address', models.CharField(max_length=250, verbose_name='Адреса')),
                ('work_time', models.CharField(max_length=100, verbose_name='Графік роботи')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Зображення')),
            ],
        ),
    ]
