# Generated by Django 5.1.9 on 2025-06-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='contact_info',
            field=models.CharField(blank=True, max_length=250, verbose_name='Контактні дані'),
        ),
    ]
