# Generated by Django 5.1.9 on 2025-05-20 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип техніки')),
                ('producer', models.CharField(max_length=100, verbose_name='Виробник')),
            ],
        ),
        migrations.CreateModel(
            name='Favors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_f', models.CharField(max_length=100, verbose_name='Назва послуги')),
                ('description_f', models.TextField(verbose_name='Опис послуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
                ('duration', models.CharField(max_length=100, verbose_name='Орієнтовний час виконання')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='favors/')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favors.equipmenttype', verbose_name='Тип техніки')),
            ],
        ),
    ]
