# Generated by Django 5.1.9 on 2025-05-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Виробник')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='favors',
            name='image',
        ),
        migrations.RemoveField(
            model_name='favors',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='favors',
            name='description_f',
            field=models.CharField(max_length=250, verbose_name='Опис послуги'),
        ),
        migrations.AlterField(
            model_name='favors',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Ціна'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='producers',
            field=models.ManyToManyField(to='favors.producer', verbose_name='Виробники'),
        ),
    ]
