# Generated by Django 5.1.9 on 2025-05-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favors', '0002_producer_remove_equipmenttype_producer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_types/', verbose_name='Зображення типу техніки'),
        ),
        migrations.AddField(
            model_name='favors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='favors/', verbose_name='Фото послуги'),
        ),
        migrations.AddField(
            model_name='producer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='producers/', verbose_name='Логотип виробника'),
        ),
    ]
