# Generated by Django 5.1.9 on 2025-06-02 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_service_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ваше ім’я')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('description', models.TextField(verbose_name='Опис проблеми')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Сервіс')),
            ],
        ),
    ]
