# Generated by Django 5.1.9 on 2025-06-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('completed', 'Завершено'), ('rejected', 'Відхилено')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
